name: My First Github Action
on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: setup java 21
              uses: actions/setup-java@v6
              with:
                  java-version: "21"
                  distribution: "temurin"
                  #   cache: maven

            # - name: Build java application
            #   run: mvn clean package

            # - name: Build docker image
            #   run: docker build -t my-java-app:latest .

            - name: checkout java version
              run: java --version

            - name: run java application
              run: java src/myapp.java
